### PR TITLE
Non existant directory check

### LINKED ISSUE #1400: ascent crash while trying to write image to non existent directory
We think that using:

```
image_prefix: "mydir/mypng"
```

Where `mydir` doesn't exist, lead to a crash.

We should error, not crash.

### PR DESCRIPTION
**Pull request by emily-howell**

### CODE REVIEW

File: src/libs/ascent/runtimes/flow_filters/ascent_runtime_rendering_filters.cpp [hunk 1]
```diff
@@ -1052,8 +1052,8 @@ DefaultRender::verify_params(const conduit::Node &params,
                              conduit::Node &info)
 {
     info.reset();
-    bool res = check_string("image_name",params, info, false);
-    res &= check_string("image_prefix",params, info, false);
+    bool res = check_path("image_name",params, info, false);
+    res &= check_path("image_prefix",params, info, false);
```
Comment (cyrush) [inline src/libs/ascent/runtimes/flow_filters/ascent_runtime_rendering_filters.cpp]: I think we should check this on execution, not on verify params.
We should also only check on rank 0 :-)

**Comment by emily-howell** [comment]
@cyrush This is ready for review again :) 

It will conflict with my other PR since I touch `DefaultRender::execute` in both so I would appreciate this one going in first.

File: src/libs/ascent/runtimes/flow_filters/ascent_runtime_utils.cpp [hunk 2]
```diff
@@ -56,6 +62,39 @@ std::string output_dir(const std::string file_name)
...
+
+bool check_dir_path_exists(const std::string file_path, int mpi_comms_id, conduit::Node &err_msg)
+{
+  int rank = 0;
+#ifdef ASCENT_MPI_ENABLED
+  MPI_Comm mpi_comm = MPI_Comm_f2c(mpi_comms_id);
+  MPI_Comm_rank(mpi_comm, &rank);
+#endif
+
+  int res = true;
```
Comment (cyrush) [inline src/libs/ascent/runtimes/flow_filters/ascent_runtime_utils.cpp]: minor suggestion:
Use 1/0 b/c the type is an int. 

Using true and false is more readable, but it makes me think we are using bools, which we don't want to do for MPI calls.

**Review by cyrush — APPROVED** [review]
Looks good, on minor suggestion which we can discuss if you think we should keep as is.
